### PR TITLE
Add Item: ClipBoardMonitor

### PR DESCRIPTION
**Pull request by cxumol**
add ClipBoardMonitor into Scripts - Clipboard section.

* [ClipBoardMonitor](https://github.com/536/ClipBoardMonitor) - Monitor clipboard changes, showing a tooltip of word counting for text or a temporary GUI for pictures.

### CODE REVIEW

**Comment by joedf** [comment]
Sounds great! 👍 
Could you make a forum post for it?

**Comment by cxumol** [comment]
I'm just a user finding this script pretty handy. I would recommend the author @536 to post on forum if he/she wants.

**Comment by joedf** [comment]
Ahhh okay, I see. 👍

**Comment by hi5** [comment]
@cxumol perhaps report to @536
1. The script says "words copied" but that is not correct, should be characters copied. Or the code changed to make it count words not just StrLen() 
2. The script doesn't work out of the box for me, I have to manually `#include lib\gdip_min.ahk`
3. The "cache/thumbs" isn't automatically created, nor does it seem to clean up that folder so you may end up with a large folder after a while
4. The Gdi "thumb" preview doesn't work for me, the entire screen dims but nothing is shown, when I edit the coordinates in Gui Show and make it much smaller and give it fixed position I see the screenshot. Might be more useful to have it actually be a thumbnail and also shown at a fixed position on the screen.
5. Having #NoTray is a bit annoying, you can't close the script
6. There is an "ClipBoardMonitor.ico" but that isn't used so Menu TrayIcon should be added (and remove the #NoTray of course)

Just my 2cts :)

**Comment by joedf** [comment]
So somewhat lacking, vote for removal. Unless we get something, or repo that is more refined...

**Comment by 536** [comment]
@cxumol @hi5 Thanks for your trying ClipboardMonitor and the recommendation, @joedf I was not avaliabe last week, sorry for being delayed. 

@hi5 I have made some changes and updated the readme, I'll appreciate it if you want to test it wheather it's good now. Here are some changes according to your report:
1. "Monitor clipboard changes, showing a tooltip for Texts or a temporary GUI for Pictures.";
2. gdip lib changed;
3. cache folder need to be created manully, noted in readme.md;
4. *still origin code*, I'm not sure if your using multiple screens, you can change the code temporarily;
5. "#NoTray" is commented out;
6. "ClipBoardMonitor.ico" deleted.

Thanks again.

**Comment by hi5** [comment]
Just works now and clear(er) instructions. The Icon was nice so you could add that back in :)

**Comment by 536** [comment]
Done

**Comment by joedf** [comment]
Great work :+1:

**Pull request merged**
