### PR TITLE
#102 remove badges

### PR DESCRIPTION
**Pull request by hoppfrosch**

### CODE REVIEW

**Comment by hi5** [comment]
Thanks - I already miss your old Avatar :-)

**Comment by hoppfrosch** [comment]
A new face! But a frog stays a frog ... ;-)

**Comment by joedf** [comment]
haha :-D

**Comment by hi5** [comment]
It has a [hypnotoad](http://i.imgur.com/z2b3ZDW.gif) look to it... :fearful:

**Comment by hoppfrosch** [comment]
AI would like to be a toad - but I'm a frog! Laughing Frog

**Pull request merged**
