### PR TITLE
Add highlight.js

### PR DESCRIPTION
**Pull request by J2TeaM**

### CODE REVIEW

**Comment by hi5** [comment]
Highlighting seems to be a bit rudimentary according to the demo, but OK, could be added.

Could you change the order, we try to list them in alphabetical order.

* highlight.js
* PrismJs
* Syntax Highlighter

**Comment by J2TeaM** [comment]
@hi5 Done! :white_check_mark:

**Comment by joedf** [comment]
Hmm there's a merge conflict...

**Comment by hi5** [comment]
There seems to be a conflict, might be best if you revolve it. On line 173 you have

    #### Web Syntax Highlighters

which should be

    ### Web Syntax Highlighters

e.g. one less # 

Perhaps reword the description to ```A syntax highlighter written in JavaScript supporting more than 130 languages (including AutoHotkey).```

**Pull request closed without merging**
