### PR TITLE
Remove gh-pages

### PR DESCRIPTION
**Pull request by hoppfrosch**
* Removed gh-pages badge from README.md
* Removed link to website from github-page (repository description)
* Removed branch "gh_pages" - this makes gh-pages disappear

### CODE REVIEW

**Comment by hoppfrosch** [comment]
Added tag "Removed_gh_pages" to be able to resurrect latest gh_pages

**Comment by joedf** [comment]
I loved the fact that it is still available for resurrection :smile:

**Comment by vasili111** [comment]
>I loved the fact that it is still available for resurrection :smile:

Agree :)

**Comment by hi5** [comment]
:walking: :skull:

**Pull request merged**
